const number1 = 60;
const number2 = 40;
str1 = number1.toString();
sum = number1 + number2;
product = number1 * number2;
console.log(number1);
console.log(number2);
console.log(str1);
console.log(sum);
console.log(product);
